version: '1.0.{build}'

environment:
  matrix:
    - RUBY_VERSION: 23
    - RUBY_VERSION: 23-x64


artifacts:
  - path: result.json
    name: Report with slashes

  - path: result-1.json
    name: Report with back-slashes


install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec cucumber features/docs/getting_started.feature -f json -o result.json
  - bundle exec cucumber features\docs\getting_started.feature -f json -o result-1.json
  - bundle exec rake

notifications:
  - provider: Slack
    incoming_webhook:
      secure: Zj2V5eXlqH4jMNvdzMBmdLA+lr658qwlJO+o7yfvUc1TMRSLNQaId9rpVWX+FsEH6DsQxYr46BRWU0bymATBe7rf7KSkomCgsAdupvKYciI=
